### ISSUE TITLE
Add word popularity values to dictionary data

### ISSUE THREAD

**Issue by stevehopkinson** [fac-u/autocompleter#2]
Word API can provide word frequency information: http://blog.wordsapi.com

**Comment by stevehopkinson** [comment]
Wikipedia page here: https://en.wikipedia.org/wiki/Word_lists_by_frequency

**Comment by SavageWilliam** [comment]
parsing our excel file http://codetheory.in/parse-read-excel-files-xls-xlsx-javascript/

**Comment by stevehopkinson** [comment]
Done - parsed excel file from http://www.newgeneralservicelist.org/s/NGSL-101-with-SFI.xlsx using https://shancarter.github.io/mr-data-converter/
