### ISSUE TITLE
Input box width

### ISSUE THREAD

**Issue by marisid** [fac-u/autocompleter#78]
Given that there is no limit in the number of characters you can type in the input field, it would be maybe better to increase the width?

**Comment by SavageWilliam** [comment]
The focus remains at the end of the input - I'll open this to debate with the team... options:
- [x] medium size box FIXED
- [ ] larger fixed box
- [ ] small inital box which gets larger to display all of input
- [ ] other

@stevehopkinson @jsms90 @lucymonie 

(I kind of just wanted to practise these checkboxes)
