### ISSUE TITLE
Front-end suggestions

### ISSUE THREAD

**Issue by marisid** [fac-u/autocompleter#89]
- HTML semantics: you use an id called "leftAlign" which refers to a section that is centrally aligned. Am I missing something?
- Since you are updating the DOM with up to 5 suggested list items, you could have 5 list items in your html and then update their content through js without creating new elements because that requires more effort in terms of DOM 'repainting'. (an issue we got in my previous team project actually :smile:)

**Comment by stevehopkinson** [comment]
Hi Marina - actually, we're only updating the DOM once (we swap out the entire UL element in one go). Updating the contents of five elements individually in the HTML would actually cause the DOM to refresh five times!

**Comment by jsms90** [comment]
@marisid Good point about semantics though :+1:

**Comment by lucymonie** [comment]
Thanks @marisid.
